const {expect} = require('chai')
const {sizes, imgSizes} = require('../constants/units')
const {imgSize, h, m, mb, ml, mr, mt, mx, my, p, pb, pl, pr, pt, px, py, w, roundSize} = require('../front/sizes')

describe('units', () => {

    describe('roundSizes', () => {

        const limits = [50, 100, 150, 200, 300, 400, 500, 600]

        it('should pass fro s < limits[0]', () => {
            expect(roundSize(42, limits)).to.equal("50")
        })

        it('should pass for in-between value', () => {
            expect(roundSize(244, limits)).to.equal("300")
        })

        it('should pass return null string', () => {
            expect(roundSize(244, [])).to.equal("")
        })

        it('should pass return last limit', () => {
            expect(roundSize(760, limits)).to.equal("600")
        })
    })


    describe('sizes', () => {

        it('should return the right size', () => {
            expect(sizes['xx-sm']).to.equal('4')
            expect(sizes['x-sm']).to.equal('6')
            expect(sizes['sm']).to.equal('8')
            expect(sizes['md']).to.equal('12')
            expect(sizes['lg']).to.equal('16')
            expect(sizes['x-lg']).to.equal('24')
            expect(sizes['xx-lg']).to.equal('32')
            expect(sizes['hero']).to.equal('48')
            expect(sizes['jumbo']).to.equal('64')
            expect(sizes['huge']).to.equal('80')
        })
    })

    describe('imgSizes', () => {

        it('should return the right image sizes', () => {
            expect(imgSizes['x-sm']).to.equal('50')
            expect(imgSizes['sm']).to.equal('100')
            expect(imgSizes['md']).to.equal('200')
            expect(imgSizes['lg']).to.equal('400')
            expect(imgSizes['x-lg']).to.equal('500')
            expect(imgSizes['xx-lg']).to.equal('600')
            expect(imgSizes['jumbo']).to.equal('800')
        })
    })

    describe('imgSize', () => {

        it('should return the right image sizes', () => {
            expect(imgSize('x-sm')).to.equal('50')
            expect(imgSize('sm')).to.equal('100')
            expect(imgSize('md')).to.equal('200')
            expect(imgSize('lg')).to.equal('400')
            expect(imgSize('x-lg')).to.equal('500')
            expect(imgSize('xx-lg')).to.equal('600')
            expect(imgSize('jumbo')).to.equal('800')
        })
    })

    describe('w', () => {

        it('should return the right width', () => {
            expect(w('xx-sm')).to.equal('4')
            expect(w('x-sm')).to.equal('6')
            expect(w('sm')).to.equal('8')
            expect(w('md')).to.equal('12')
            expect(w('lg')).to.equal('16')
            expect(w('x-lg')).to.equal('24')
            expect(w('xx-lg')).to.equal('32')
            expect(w('hero')).to.equal('48')
            expect(w('jumbo')).to.equal('64')
            expect(w('huge')).to.equal('80')
        })
    })

    describe('h', () => {

        it('should return the right height', () => {
            expect(h('xx-sm')).to.equal('4')
            expect(h('x-sm')).to.equal('6')
            expect(h('sm')).to.equal('8')
            expect(h('md')).to.equal('12')
            expect(h('lg')).to.equal('16')
            expect(h('x-lg')).to.equal('24')
            expect(h('xx-lg')).to.equal('32')
            expect(h('hero')).to.equal('48')
            expect(h('jumbo')).to.equal('64')
            expect(h('huge')).to.equal('80')
        })
    })

    describe('margin', () => {

        it('should return the right padding', () => {
            expect(m('xx-sm')).to.equal('4')
            expect(m('x-sm')).to.equal('6')
            expect(m('sm')).to.equal('8')
            expect(m('md')).to.equal('12')
            expect(m('lg')).to.equal('16')
            expect(m('x-lg')).to.equal('24')
            expect(m('xx-lg')).to.equal('32')
            expect(m('hero')).to.equal('48')
            expect(m('jumbo')).to.equal('64')
            expect(m('huge')).to.equal('80')
            expect(mb('xx-sm')).to.equal('4')
            expect(mb('x-sm')).to.equal('6')
            expect(mb('sm')).to.equal('8')
            expect(mb('md')).to.equal('12')
            expect(mb('lg')).to.equal('16')
            expect(mb('x-lg')).to.equal('24')
            expect(mb('xx-lg')).to.equal('32')
            expect(mb('hero')).to.equal('48')
            expect(mb('jumbo')).to.equal('64')
            expect(mb('huge')).to.equal('80')
            expect(mt('xx-sm')).to.equal('4')
            expect(mt('x-sm')).to.equal('6')
            expect(mt('sm')).to.equal('8')
            expect(mt('md')).to.equal('12')
            expect(mt('lg')).to.equal('16')
            expect(mt('x-lg')).to.equal('24')
            expect(mt('xx-lg')).to.equal('32')
            expect(mt('hero')).to.equal('48')
            expect(mt('jumbo')).to.equal('64')
            expect(mt('huge')).to.equal('80')
            expect(ml('xx-sm')).to.equal('4')
            expect(ml('x-sm')).to.equal('6')
            expect(ml('sm')).to.equal('8')
            expect(ml('md')).to.equal('12')
            expect(ml('lg')).to.equal('16')
            expect(ml('x-lg')).to.equal('24')
            expect(ml('xx-lg')).to.equal('32')
            expect(ml('hero')).to.equal('48')
            expect(ml('jumbo')).to.equal('64')
            expect(ml('huge')).to.equal('80')
            expect(mr('xx-sm')).to.equal('4')
            expect(mr('x-sm')).to.equal('6')
            expect(mr('sm')).to.equal('8')
            expect(mr('md')).to.equal('12')
            expect(mr('lg')).to.equal('16')
            expect(mr('x-lg')).to.equal('24')
            expect(mr('xx-lg')).to.equal('32')
            expect(mr('hero')).to.equal('48')
            expect(mr('jumbo')).to.equal('64')
            expect(mr('huge')).to.equal('80')
            expect(mx('xx-sm')).to.equal('4')
            expect(mx('x-sm')).to.equal('6')
            expect(mx('sm')).to.equal('8')
            expect(mx('md')).to.equal('12')
            expect(mx('lg')).to.equal('16')
            expect(mx('x-lg')).to.equal('24')
            expect(mx('xx-lg')).to.equal('32')
            expect(mx('hero')).to.equal('48')
            expect(mx('jumbo')).to.equal('64')
            expect(mx('huge')).to.equal('80')
            expect(my('xx-sm')).to.equal('4')
            expect(my('x-sm')).to.equal('6')
            expect(my('sm')).to.equal('8')
            expect(my('md')).to.equal('12')
            expect(my('lg')).to.equal('16')
            expect(my('x-lg')).to.equal('24')
            expect(my('xx-lg')).to.equal('32')
            expect(my('hero')).to.equal('48')
            expect(my('jumbo')).to.equal('64')
            expect(my('huge')).to.equal('80')
        })
    })

    describe('p', () => {

        it('should return the right padding', () => {
            expect(p('xx-sm')).to.equal('4')
            expect(p('x-sm')).to.equal('6')
            expect(p('sm')).to.equal('8')
            expect(p('md')).to.equal('12')
            expect(p('lg')).to.equal('16')
            expect(p('x-lg')).to.equal('24')
            expect(p('xx-lg')).to.equal('32')
            expect(p('hero')).to.equal('48')
            expect(p('jumbo')).to.equal('64')
            expect(p('huge')).to.equal('80')
            expect(pb('xx-sm')).to.equal('4')
            expect(pb('x-sm')).to.equal('6')
            expect(pb('sm')).to.equal('8')
            expect(pb('md')).to.equal('12')
            expect(pb('lg')).to.equal('16')
            expect(pb('x-lg')).to.equal('24')
            expect(pb('xx-lg')).to.equal('32')
            expect(pb('hero')).to.equal('48')
            expect(pb('jumbo')).to.equal('64')
            expect(pb('huge')).to.equal('80')
            expect(pt('xx-sm')).to.equal('4')
            expect(pt('x-sm')).to.equal('6')
            expect(pt('sm')).to.equal('8')
            expect(pt('md')).to.equal('12')
            expect(pt('lg')).to.equal('16')
            expect(pt('x-lg')).to.equal('24')
            expect(pt('xx-lg')).to.equal('32')
            expect(pt('hero')).to.equal('48')
            expect(pt('jumbo')).to.equal('64')
            expect(pt('huge')).to.equal('80')
            expect(pl('xx-sm')).to.equal('4')
            expect(pl('x-sm')).to.equal('6')
            expect(pl('sm')).to.equal('8')
            expect(pl('md')).to.equal('12')
            expect(pl('lg')).to.equal('16')
            expect(pl('x-lg')).to.equal('24')
            expect(pl('xx-lg')).to.equal('32')
            expect(pl('hero')).to.equal('48')
            expect(pl('jumbo')).to.equal('64')
            expect(pl('huge')).to.equal('80')
            expect(pr('xx-sm')).to.equal('4')
            expect(pr('x-sm')).to.equal('6')
            expect(pr('sm')).to.equal('8')
            expect(pr('md')).to.equal('12')
            expect(pr('lg')).to.equal('16')
            expect(pr('x-lg')).to.equal('24')
            expect(pr('xx-lg')).to.equal('32')
            expect(pr('hero')).to.equal('48')
            expect(pr('jumbo')).to.equal('64')
            expect(pr('huge')).to.equal('80')
            expect(px('xx-sm')).to.equal('4')
            expect(px('x-sm')).to.equal('6')
            expect(px('sm')).to.equal('8')
            expect(px('md')).to.equal('12')
            expect(px('lg')).to.equal('16')
            expect(px('x-lg')).to.equal('24')
            expect(px('xx-lg')).to.equal('32')
            expect(px('hero')).to.equal('48')
            expect(px('jumbo')).to.equal('64')
            expect(px('huge')).to.equal('80')
            expect(py('xx-sm')).to.equal('4')
            expect(py('x-sm')).to.equal('6')
            expect(py('sm')).to.equal('8')
            expect(py('md')).to.equal('12')
            expect(py('lg')).to.equal('16')
            expect(py('x-lg')).to.equal('24')
            expect(py('xx-lg')).to.equal('32')
            expect(py('hero')).to.equal('48')
            expect(py('jumbo')).to.equal('64')
            expect(py('huge')).to.equal('80')
        })
    })
})