export const CONFIRM = 'CONFIRM'
export const POST = 'POST'
export const GET = 'GET'
export const DELETE = 'DELETE'
export const PATCH = 'PATCH'
export const ANONYMOUS = 'ANONYMOUS'
export const REGISTERED = 'registered'
export const AUTHORIZATION = 'Authorization'

// sizes
export const XX_SM = 'xx-sm'
export const X_SM = 'x-sm'
export const SM = 'sm'
export const MD = 'md'
export const LG ='lg'
export const X_LG = 'x-lg'
export const XX_LG = 'xx-lg'
export const HERO = 'hero'
export const JUMBO = 'jumbo'
export const HUGE = 'huge'