version: '3'
services:
  worker:
    image: worker:latest
    container_name: worker
    env:
      WORKER_ENV=DOCKER
    ports:
      - "4848:4848"
    volumes:
      - ../__common__/__config__:/home/python3/__config__
      - ../__common__/__storage__:/home/python3/__storage__
      - ../__common__/__resources__:/home/python3/__resources__
